# Generated by Django 2.2.4 on 2020-04-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200410_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='contry',
            new_name='country',
        ),
    ]
